[project]
name = "hexlet-code"
version = "0.1.0"
description = "Page Analyzer project"
package-mode = false
authors = [
  { name = "trun", email = "e.s.trunov@gmail.com" }
]
readme = "README.md"
dependencies = [
    "flask",
    "psycopg2-binary",
    "validators",
    "requests",
    "beautifulsoup4",
    "python-dotenv",
    "gunicorn"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
