[project]
name = "hexlet-code"
version = "0.1.0"
description = "Page Analyzer project"
authors = [
  { name = "trun", email = "e.s.trunov@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10,<3.11"

dependencies = [
  "flask",
  "psycopg2-binary",
  "validators",
  "requests",
  "beautifulsoup4",
  "python-dotenv",
  "gunicorn",
]

[tool.poetry]
packages = [{ include = "page_analyzer" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
