exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info",
]

target-version = "py310"

select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

ignore = [
    "E501",   # line too long (исправлено автоматически)
    "B008",   # do not perform function calls in argument defaults
    "C901",   # too complex (пока оставим)
]

max-complexity = 10

line-length = 100

[tool.ruff.isort]
known-first-party = ["page_analyzer"]
combine-as-imports = true
